# Accessing Elements in NumPy Arrays

This lesson covers:

* Accessing specific elements in NumPy arrays

Accessing elements in an array or a DataFrame is a common task. To begin this lesson, clear the
workspace set up some vectors and a $5\times5$ array. These vectors and matrix will make it easy
to determine which elements are selected by a command.

In [1]:
import numpy as np
import pandas as pd

x = np.arange(25).reshape((5,5))  
y = np.arange(5)
# The -1 tells numpy to automatically compute the size of
# the dimension using the remaining elements, in this case, 5
z = np.arange(5).reshape((-1, 1))

x_df = pd.DataFrame(x)
x_named = pd.DataFrame(x, index=['r0','r1','r2','r3','r4'],
                       columns=['c0','c1','c2','c3','c4'])
y_s = pd.Series(y)
y_named = pd.Series(y, index=['r0','r1','r2','r3','r4'])

print(f'x = {x}')
print(f'y = {y}')
print(f'z = {z}')

print()
print(f'x_df = \n{x_df}')
print(f'y_s = \n{y_s}')

print()
print(f'x_named = \n{x_named}')
print(f'y_named = \n{y_named}')

x = [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
y = [0 1 2 3 4]
z = [[0]
 [1]
 [2]
 [3]
 [4]]

x_df = 
    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
y_s = 
0    0
1    1
2    2
3    3
4    4
dtype: int32

x_named = 
    c0  c1  c2  c3  c4
r0   0   1   2   3   4
r1   5   6   7   8   9
r2  10  11  12  13  14
r3  15  16  17  18  19
r4  20  21  22  23  24
y_named = 
r0    0
r1    1
r2    2
r3    3
r4    4
dtype: int32



## Zero-based indexing
Python indexing is 0 based so that the first element has position `0`, the second has position `1`
and so on until the last element has position `n-1` in an array that contains `n` elements in
total.

## Problem: Picking an Element out of a Matrix
1. Select the third element of all three, x, y, and z. 
2. Select the 11$^{\text{th}}$ element of x.
3. Using double index notation, select the (0,2) and the (2,0) element of x.

**Issues to ponder**

* Which index is rows and which index is columns?
* Does NumPy count across first then down or down first then across? 

In [2]:
print(x.flat[2])
print(y.flat[2])
print(z.flat[2])

2
2
2


In [3]:
# Incorrect
print(x[2])
print(y[2])
print(z[2])


[10 11 12 13 14]
2
[2]


In [4]:
print(x.flat[10])  # 11th element is position 10

10


In [5]:
print(x[0, 2])
print(x[2, 0])

2
10


## Problem: Selecting Entire Rows
1. Select the 2nd row of x using the colon (:) operator.
2. Select the 2nd element of z and y using the same syntax.

**Issues to ponder**

* What happens to the output in each case? 


In [6]:
print(x[1, :])
print(x[1])
print(y[1:2])
print(z[1:2, :])
print(z[1:2])

[5 6 7 8 9]
[5 6 7 8 9]
[1]
[[1]]
[[1]]


## Problem: Selecting Entire Columns
Select the 2nd column of x using the colon (:) operator. 

In [7]:
print(x[:, 1])

[ 1  6 11 16 21]


In [8]:
print(x[:, [1]])
print(x[:, 1:2])


[[ 1]
 [ 6]
 [11]
 [16]
 [21]]
[[ 1]
 [ 6]
 [11]
 [16]
 [21]]


## Problem: Selecting Specific Rows or Columns
1. Select the 2nd and 3rd columns of x using the colon (:) operator.
2. Select the 2nd and 4th rows of x. 
3. Combine these be combined to select columns 2 and 3 and rows 2 and 4. 

In [9]:
print(x[:, 1:3])

[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]
 [21 22]]


In [10]:
print(x[[1, 3], :])
print(x[1:4:2, :])

[[ 5  6  7  8  9]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [15 16 17 18 19]]


In [11]:
print(x[1:4:2, 1:3])

# Wrong
print(x[[1, 3],[1, 2]])

# Right
print(x[[1,3], 1:3])

[[ 6  7]
 [16 17]]
[ 6 17]
[[ 6  7]
 [16 17]]


## Problem: Use `ix_` to select arbitrary rows and columns
Use `ix_` to select the 2nd and 4th rows and 1st and 3rd columns of `x`.

In [12]:
# Must use ix_ when both selectors are "fancy" to get blocks
x[np.ix_([1, 3],[1, 2])]

array([[ 6,  7],
       [16, 17]])

In [13]:
# Also correct, but hard to get right
x[[[1,1],[3,3]],[[1,2],[1,2]]]

array([[ 6,  7],
       [16, 17]])