# Numeric Indexing of DataFrames

This lesson covers:

* Accessing specific elements in DataFrames using numeric indices

Accessing elements in a DataFrame is a common task. To begin this lesson, clear the
workspace set up some vectors and a $5\times5$ array. These vectors and matrix will make it easy
to determine which elements are selected by a command.

In [1]:
import numpy as np
import pandas as pd

x = np.arange(25).reshape((5,5))  
y = np.arange(5)


x_df = pd.DataFrame(x)
x_named = pd.DataFrame(x, index=['r0','r1','r2','r3','r4'],
                       columns=['c0','c1','c2','c3','c4'])
y_s = pd.Series(y)
y_named = pd.Series(y, index=['r0','r1','r2','r3','r4'])

print(f'x = {x}')
print(f'y = {y}')

print()
print(f'x_df = \n{x_df}')
print(f'y_s = \n{y_s}')

print()
print(f'x_named = \n{x_named}')
print(f'y_named = \n{y_named}')

x = [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
y = [0 1 2 3 4]

x_df = 
    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
y_s = 
0    0
1    1
2    2
3    3
4    4
dtype: int32

x_named = 
    c0  c1  c2  c3  c4
r0   0   1   2   3   4
r1   5   6   7   8   9
r2  10  11  12  13  14
r3  15  16  17  18  19
r4  20  21  22  23  24
y_named = 
r0    0
r1    1
r2    2
r3    3
r4    4
dtype: int32


## Problem: Picking an Element out of a Matrix

Using double index notation, select the (0,2) and the (2,0) element of `x_named`.

In [2]:
print(x_named.iloc[0, 2])
print(x_named.iloc[2, 0])


2
10


## Problem: Selecting Entire Rows
1. Select the 2nd row of `x_named` using the colon (:) operator.
2. Select the 2nd element of `y_named` using the same syntax.


In [3]:
print(x_df.iloc[1, :])
print(x_df.iloc[1])
print(y_named.iloc[1:2])

0    5
1    6
2    7
3    8
4    9
Name: 1, dtype: int32
0    5
1    6
2    7
3    8
4    9
Name: 1, dtype: int32
r1    1
dtype: int32


## Problem: Selecting Entire Columns
Select the 2nd column of `x_named` using the colon (:) operator. 

In [4]:
print(x_named.iloc[:, 1])

r0     1
r1     6
r2    11
r3    16
r4    21
Name: c1, dtype: int32


In [5]:
print(x_named.iloc[:, [1]])
print(x_named.iloc[:, 1:2])


    c1
r0   1
r1   6
r2  11
r3  16
r4  21
    c1
r0   1
r1   6
r2  11
r3  16
r4  21


## Problem: Selecting Specific Columns
Select the 2nd and 3rd columns of `x_named` using the colon (:) operator.

In [6]:
print(x_named.iloc[:, 1:3])

    c1  c2
r0   1   2
r1   6   7
r2  11  12
r3  16  17
r4  21  22


## Problem: Select Specific Rows

Select the 2nd and 4th rows of `x_named`. 
Combine these be combined to select columns 2 and 3 and rows 2 and 4. 


In [7]:
print(x_named.iloc[[1, 3], :])
print(x_named.iloc[1:4:2, :])

    c0  c1  c2  c3  c4
r1   5   6   7   8   9
r3  15  16  17  18  19
    c0  c1  c2  c3  c4
r1   5   6   7   8   9
r3  15  16  17  18  19


## Problem: Select Specific Rows and Columns

Combine these be combined to select columns 2 and 3 and rows 2 and 4. 

In [8]:
print(x_named.iloc[1:4:2, 1:3])

# Wrong
print(x_named.iloc[[1, 3],[1, 2]])

# Right
print(x_named.iloc[[1,3], 1:3])

    c1  c2
r1   6   7
r3  16  17
    c1  c2
r1   6   7
r3  16  17
    c1  c2
r1   6   7
r3  16  17


## Problem: Select arbitrary rows and columns
Select the 2nd and 4th rows and 1st and 3rd columns of `x`.

**Note**: This is the only important difference with NumPy.  Arbitrary row/column
selection using `DataFrame.iloc` is simpler but less flexible.

In [9]:
x_named.iloc[[1, 3],[1, 2]]

c1  c2
r1   6   7
r3  16  17