# Boolean Selection 

This lesson covers:

* Boolean selection
* `where`

Begin by loading the data in momentum.csv.


In [1]:
# Setup: Load the momentum data

import numpy as np
import pandas as pd

momentum = pd.read_csv("data/momentum.csv", index_col="date", parse_dates=True)

print(momentum.head())


            mom_01  mom_02  mom_03  mom_04  mom_05  mom_06  mom_07  mom_08  \
date                                                                         
2016-01-04    0.67   -0.03   -0.93   -1.11   -1.47   -1.66   -1.40   -2.08   
2016-01-05   -0.36    0.20   -0.37    0.28    0.16    0.18   -0.22    0.25   
2016-01-06   -4.97   -2.33   -2.60   -1.16   -1.70   -1.45   -1.15   -1.46   
2016-01-07   -4.91   -1.91   -3.03   -1.87   -2.31   -2.30   -2.70   -2.31   
2016-01-08   -0.40   -1.26   -0.98   -1.26   -1.13   -1.02   -0.96   -1.42   

            mom_09  mom_10  
date                        
2016-01-04   -1.71   -2.67  
2016-01-05    0.29    0.13  
2016-01-06   -1.14   -0.45  
2016-01-07   -2.36   -2.66  
2016-01-08   -0.94   -1.32  


## Problem: Selecting rows with boolean conditions

Select the rows in `momentum` where all returns on a day are negative.

In [2]:
momentum.loc[(momentum < 0).all(axis=1)]


mom_01  mom_02  mom_03  mom_04  mom_05  mom_06  mom_07  mom_08  \
date                                                                         
2016-01-06   -4.97   -2.33   -2.60   -1.16   -1.70   -1.45   -1.15   -1.46   
2016-01-07   -4.91   -1.91   -3.03   -1.87   -2.31   -2.30   -2.70   -2.31   
2016-01-08   -0.40   -1.26   -0.98   -1.26   -1.13   -1.02   -0.96   -1.42   
2016-01-13   -4.88   -3.06   -2.70   -2.00   -2.34   -2.18   -2.44   -2.77   
2016-01-15   -3.85   -2.87   -1.92   -2.09   -1.38   -2.46   -1.88   -2.23   
...            ...     ...     ...     ...     ...     ...     ...     ...   
2017-10-25   -0.77   -0.72   -0.33   -0.83   -0.28   -0.52   -0.23   -0.48   
2017-10-30   -0.01   -0.72   -0.50   -0.91   -0.73   -0.27   -0.42   -0.04   
2017-11-15   -0.20   -0.64   -0.65   -0.13   -0.37   -0.41   -0.75   -0.37   
2017-12-14   -1.20   -0.99   -0.78   -0.26   -0.38   -0.41   -0.76   -0.32   
2017-12-29   -0.42   -0.61   -0.48   -0.57   -0.45   -0.41   -0.52   -0.45   

            mom_09  mom_10  
date                        
2016-01-06   -1.14   -0.45  
2016-01-07   -2.36   -2.66  
2016-01-08   -0.94   -1.32  
2016-01-13   -2.65   -3.71  
2016-01-15   -2.28   -2.40  
...            ...     ...  
2017-10-25   -0.35   -1.52  
2017-10-30   -0.41   -0.40  
2017-11-15   -0.77   -0.59  
2017-12-14   -0.60   -0.17  
2017-12-29   -0.70   -0.94  

[74 rows x 10 columns]

## Problem: Selecting rows

Select the rows in `momentum` where 50% or more of the returns on a day are negative.

In [3]:
momentum.loc[(momentum < 0).mean(axis=1) >= 0.5]


mom_01  mom_02  mom_03  mom_04  mom_05  mom_06  mom_07  mom_08  \
date                                                                         
2016-01-04    0.67   -0.03   -0.93   -1.11   -1.47   -1.66   -1.40   -2.08   
2016-01-06   -4.97   -2.33   -2.60   -1.16   -1.70   -1.45   -1.15   -1.46   
2016-01-07   -4.91   -1.91   -3.03   -1.87   -2.31   -2.30   -2.70   -2.31   
2016-01-08   -0.40   -1.26   -0.98   -1.26   -1.13   -1.02   -0.96   -1.42   
2016-01-11   -5.14   -0.81   -1.33   -0.72   -0.43    0.14    0.23    0.28   
...            ...     ...     ...     ...     ...     ...     ...     ...   
2017-12-19   -0.61    0.19   -0.41   -0.30   -0.17   -0.31   -0.41   -0.18   
2017-12-22    0.24    0.13   -0.07   -0.01   -0.08   -0.10   -0.14   -0.16   
2017-12-26    0.89    0.70    0.23   -0.03    0.10   -0.06   -0.14   -0.07   
2017-12-27   -0.58   -0.55   -0.27   -0.19   -0.14    0.18    0.18    0.10   
2017-12-29   -0.42   -0.61   -0.48   -0.57   -0.45   -0.41   -0.52   -0.45   

            mom_09  mom_10  
date                        
2016-01-04   -1.71   -2.67  
2016-01-06   -1.14   -0.45  
2016-01-07   -2.36   -2.66  
2016-01-08   -0.94   -1.32  
2016-01-11    0.29    0.33  
...            ...     ...  
2017-12-19   -0.15   -0.56  
2017-12-22   -0.05   -0.01  
2017-12-26    0.14   -0.65  
2017-12-27    0.22    0.36  
2017-12-29   -0.70   -0.94  

[243 rows x 10 columns]

## Problem: Selecting columns

Select the columns in `momentum` what have the smallest and second smallest average returns.

In [4]:
mean = momentum.mean()
mean = mean.sort_values()
mean

mom_09    0.042167
mom_07    0.051789
mom_10    0.060954
mom_08    0.062604
mom_05    0.069920
mom_04    0.079145
mom_06    0.080775
mom_03    0.089801
mom_02    0.094811
mom_01    0.101909
dtype: float64

In [6]:
momentum.loc[:, momentum.mean() < mean.iloc[2]]


mom_07  mom_09
date                      
2016-01-04   -1.40   -1.71
2016-01-05   -0.22    0.29
2016-01-06   -1.15   -1.14
2016-01-07   -2.70   -2.36
2016-01-08   -0.96   -0.94
...            ...     ...
2017-12-22   -0.14   -0.05
2017-12-26   -0.14    0.14
2017-12-27    0.18    0.22
2017-12-28    0.30    0.28
2017-12-29   -0.52   -0.70

[503 rows x 2 columns]

In [ ]:
momentum[mean.index[:2]]


## Problem: Selecting rows and columns

Select the returns for the column with the single most negative return
on days where all of the returns are negative. 

In [8]:
lowest = (momentum == momentum.min().min()).any()
lowest

mom_01     True
mom_02    False
mom_03    False
mom_04    False
mom_05    False
mom_06    False
mom_07    False
mom_08    False
mom_09    False
mom_10    False
dtype: bool

In [9]:
momentum.loc[(momentum < 0).all(axis=1), lowest]

 

mom_01
date              
2016-01-06   -4.97
2016-01-07   -4.91
2016-01-08   -0.40
2016-01-13   -4.88
2016-01-15   -3.85
...            ...
2017-10-25   -0.77
2017-10-30   -0.01
2017-11-15   -0.20
2017-12-14   -1.20
2017-12-29   -0.42

[74 rows x 1 columns]

## Problem: Selecting Elements using Logical Statements
For portfolio 1 and portfolio 10 compute the correlation when both 
returns are negative and when both are positive.


In [13]:
mom_01 = momentum.mom_01
mom_10 = momentum.mom_10

mom_01_neg = mom_01 < 0
mom_10_neg = mom_10 < 0
both_neg = mom_01_neg & mom_10_neg

momentum.loc[both_neg, ["mom_01", "mom_10"]].corr()

mom_01    mom_10
mom_01  1.000000  0.368096
mom_10  0.368096  1.000000

In [16]:
sub = momentum[["mom_01", "mom_10"]]
sub.loc[(sub > 0).all(axis=1)].corr()

mom_01    mom_10
mom_01  1.000000  0.165254
mom_10  0.165254  1.000000

In [22]:
# Setup: Reproducible random numbers

rs = np.random.RandomState(19991231)
x = rs.randint(1, 11, size=(10,3))
x

array([[ 5,  8, 10],
       [10,  5,  9],
       [ 6,  9, 10],
       [ 8,  5,  9],
       [ 2,  2,  4],
       [ 5,  6,  7],
       [10,  7,  2],
       [ 4,  3,  5],
       [ 6,  3,  9],
       [10,  1,  9]])

## Problem: Select the columns of x that means >= $E[x]$

In [25]:
x[:, x.mean(axis=0) >= 5.5]

array([[ 5, 10],
       [10,  9],
       [ 6, 10],
       [ 8,  9],
       [ 2,  4],
       [ 5,  7],
       [10,  2],
       [ 4,  5],
       [ 6,  9],
       [10,  9]])

## Problem: Select the rows of x that means >= $E[x]$

In [26]:
x[x.mean(axis=1) >= 5.5]

array([[ 5,  8, 10],
       [10,  5,  9],
       [ 6,  9, 10],
       [ 8,  5,  9],
       [ 5,  6,  7],
       [10,  7,  2],
       [ 6,  3,  9],
       [10,  1,  9]])

## Problem: Select the rows and column of x where both have means < $E[x]$

In [27]:
rows = x.mean(axis=1) >= 5.5
cols = x.mean(axis=0) >= 5.5

x[np.ix_(rows, cols)]


array([[ 5, 10],
       [10,  9],
       [ 6, 10],
       [ 8,  9],
       [ 5,  7],
       [10,  2],
       [ 6,  9],
       [10,  9]])

## Problem: Using `where`
Use `where` to select the index of the elements in portfolio 5 that are
negative. Next, use the `where` command in its two output form to determine
which elements of the portfolio return matrix are less than -2%.

In [ ]:
mom_05 = momentum.mom_05
np.where(mom_05 < 0)

In [ ]:
loc = np.where(mom_05 < 0)
mom_05.iloc[loc]

In [ ]:
loc = np.where(momentum < 0)
# Two awways, rows and columns where momentum < 0
print(loc)